exports.ResponseMessage = {
  email_already_associate_with_another_account:
    "Email already associated with another account",
  mobile_number_already_associate_with_another_account:
    "Mobile number already associated with another account",
  number_is_not_valid: "Number is not valid",
  You_ve_reached_the_maximum_OTP_check_attempts_please_try_after_some_time:
    "You've reached the maximum OTP check attempts, Please try after some time",
  You_ve_reached_the_maximum_OTP_send_attempts_please_try_after_some_time:
    "You've reached the maximum OTP send attempts, Please try after some time",
  a_free_trial_account_cannot_be_used_to_purchase_a_number:
    "A free trial account cannot be used to purchase a number.",
  You_dont_have_permission_to: "You don't have permission to",
  please_verify_your_email: "Please verify your email",
  domain_name_is_already_in_use: "Domain name is already in use",
  domain_name_is_not_available: "Domain name is not available",
  mobile_number_is_already_registered: "Mobile number is already registered",
  mobile_number_is_already_registered_please_try_with_another:
    "Mobile number is already registered, please try with another",
  successful_operation: "Successful operation",
  something_went_wrong: "Something went wrong",
  internal_server_error: "Internal server error",
  message: "Message",
  error_message: "Error message",
  email_is_not_verified: "Email is not verified",
  data_not_found: "Data not found",
  password_not_matched: "Password not matched",
  email_id_is_not_exist: "Email Id Is Not Exist..",
  success: "Success",
  image_added_successfully: "Image added successfully",
  email_verified_successfully: "Email verified successfully",
  please_enter_valid_otp: "Please enter a valid OTP",
  otp_sent_successfully: "OTP sent successfully",
  otp_sending_failed: "OTP sending failed",
  otp_not_matched: "OTP not matched",
  otp_not_updated: "OTP not updated",
  otp_not_deleted: "OTP not deleted",
  gender_updated_successfully: "Gender updated successfully",
  user_register_successfully: "User register successfully",
  email_not_register: "Email not registered",
  please_enter_valid_email_or_mobile_number:
    "Please enter a valid email or mobile number",
  please_enter_valid_mobile_number: "Please enter a mobile number",
  otp_verified_successfully: "OTP verified successfully",
  otp_verification_fail: "OTP verification fail",
  user_verification_fail: "User verification fail",
  invalid_mobile_number_or_otp: "Invalid mobile number or OTP",
  invalid_email: "Invalid email",
  invalid_email_or_password: "Invalid email or password",
  login_successfully: "Login successfully",
  get_login_successfully: "Get login successfully",
  login_fail: "Login fail",
  logout_successful: "Logout successfully",
  logout_failed: "Logout failed",
  mobile_number_verified: "Mobile number verified",
  complete_your_email_verification_first:
    "Complete your email verification first",
  email_integration_is_disabled: "Email integration is disabled",
  customer_not_found: "Customer not found",
  email_sent: "Email sent",
  email_sent_fail: "Email sent fail",
  your_email_is_already_verified: "Your email is already verified",
  invalid_password: "Invalid password",
  password_changed_successfully: "Password changed successfully",
  password_must_be_at_least_6_characters:
    "password_must_be_at_least_6_characters",
  password_not_changed: "Password not changed",
  messenger_page_not_configured: "Messenger page is not configured",
  get_exoplanets_successfully: "Get exoplanets successfully",
  get_exoplanets_quiz_successfully: "Get exoplanets wise quiz successfully",
  whatsapp_number_not_configured: "WhatsApp number is not configured",
  forgot_password_link_sent_on_your_email:
    "Forgot password link sent on your email",
  password_updated_successfully: "Password updated successfully",
  this_link_is_expired_or_invalid_please_try_again:
    "This link is expired or invalid. Please try again",
  subdomain_not_register: "Subdomain not register",
  invalid_token: "Invalid token",
  user_updated_successfully: "User updated successfully",
  user_update_failed: "User update failed",
  invalid_otp: "Invalid OTP",
  sms_received: "SMS received",
  sms_sent_successfully: "SMS sent successfully",
  attachment_sending_failed: "Attachment sending failed",
  email_received: "Email received",
  list_of_mobile_numbers: "List of mobile numbers",
  mobile_number_not_found: "Mobile number not found",
  you_already_have_a_phone_number: "You already have a phone number",
  mobile_number_purchased_successfully: "Mobile number purchased successfully",
  mobile_number_purchase_fail: "Mobile number purchase fail",
  mobile_number_release_fail: "Mobile number release fail",
  mobile_number_released_successfully: "Mobile number released successfully",
  mobile_number_no_access: "You don't have access to this number",
  mobile_number_is_not_available: "Mobile number is not available",
  this_number_is_not_available_please_select_another_number_and_try_again:
    "This Mobile number is not available, please select another number and try again",
  invalid_category_id: "Invalid category id",
  invalid_id: "Invalid id",
  invalid_imap_connection: "Invalid imap settings",
  invalid_smtp_connection: "Invalid smtp settings",
  user_created_successfully: "User created successfully",
  email_is_already_in_use: "Email is already in use",
  invalid_credentials: "Invalid credentials",
  email_or_mobile_number_is_required: "Email or Mobile number is required",
  email_or_otp_number_is_required: "Email or Otp is required",
  attachment_uploaded: "Attachment Uploaded",
  attachment_not_found: "Attachment not found",
  invalid_type_id: "Invalid type id",
  payment_initialize_successfully: "Payment initialize successfully",
  you_can_send_only_png_jpg_and_jpeg_file_only:
    "You can send .png, .jpg and .jpeg file only",
  you_can_send_only_png_and_jpeg_file_only:
    "You can send .png and .jpeg file only",
  you_can_send_text_or_attachment_at_a_time:
    "You can send text or attachment at a time",
  billing_address_updated_successfully: "Billing address updated successfully",
  invalid_to_id: "Invalid to id",
  invalid_member_id: "Invalid member id",
  invite_sent: "Invite Sent",
  Please_check_your_mobile_number_because_it_was_entered_incorrectly:
    "Please check your mobile number because it was entered incorrectly",
  your_account_has_been_Suspended: "Your account has been Suspended!",
  you_can_not_purchase_a_Free_subscription:
    "You can not purchase a Free subscription",
  you_can_not_initiate_the_chat_after_24_hours:
    "You can not initiate the chat after 24 hours",
  you_can_add_only_mp3_and_wav_file_only: "You can add .mp3 and .wav file only",
  message_read_successfully: "Message read successfully",
  message_read_failed: "Message read failed",
  this_integration_cannot_be_enabled: "This integration cannot be enabled",
  your_application_has_been_submitted: "Your application has been submitted!",
  a2p_registration_failed: "A2P registration failed",
  failed: "failed",
  user_not_found: "User not found",
  invalid_credentials: "Invalid credentials",
  google_data: "Google Data",
  data_added: "Data added successfully",
  delete_furniture_successfully: "Delete Furniture successfully",
  get_by_id_furniture_successfully: "Get By Id Furniture successfully",
  please_enter_data: "Please enter data",
  include_in_price_added: "Include In Price details added successfully",
  get_include_in_price_successfully: "Get include in price data successfully",
  get_by_id_include_in_price_successfully:
    "Get By Id include in price successfully",
  update_include_in_price_successfully:
    "Update include in price data successfully",
  delete_include_in_price_successfully: "Delete include in price successfully",
  include_in_price_active_successfully: "Include in price active successfully",
  include_in_price_inactive_successfully:
    "Include in price inactive successfully",
  extra_price_added: "Extra Price details added successfully",
  get_extra_price_successfully: "Get Extra price data successfully",
  get_by_id_extra_price_successfully: "Get By Id Extra price successfully",
  update_extra_price_successfully: "Update Extra price data successfully",
  delete_extra_price_successfully: "Delete Extra price successfully",
  extra_price_active_successfully: "Extra price active successfully",
  extra_price_inactive_successfully: "Extra price inactive successfully",
  ShortList_data_added: "Short List added successfully",
  get_short_list_data_added: "Get Short list data successfully",
  delete_short_list_successfully: "Delete short list successfully",
  place_near_by_added: "Place near by details added successfully",
  get_place_near_by_successfully: "Get Place near by data successfully",
  get_by_id_place_near_by_successfully: "Get By Id Place near by successfully",
  update_place_near_by_successfully: "Update Place near by data successfully",
  delete_place_near_by_successfully: "Delete Place near by successfully",
  all_fields_are_required: "All fields are required",
  plan_created_successfully: "Plan created successfully",
  get_plan_successfully: "Get plan successfully",
  please_try_to_correct_credentials: "Please try to correct credentials",
  user_mobile_number_register_successfully: "Please try to correct credentials",
  banner_added_successfully: "Banner added successfully",
  banner_updated_successfully: "Banner updated successfully",
  banner_deleted_successfully: "Banner deleted successfully",
  banner_image_not_updated: "Banner image not updated",
  get_banner_successfully: "Get banner data successfully",
  banner_not_found: "Banner not found",
  category_added_successfully: "Category added successfully",
  category_get_successfully: "Category get data successfully",
  category_data_not_found: "Category data not found",
  category_update_successfully: "Category update successfully",
  category_delete_successfully: "Category delete successfully",
  category_delete_successfully: "Category delete successfully",
  category_delete_fail: "Category delete fail",
  category_update_fail: "Category update fail",
  driver_added_successfully: "Driver added successfully",
  driver_updated_successfully: "Driver updated successfully",
  driver_deleted_successfully: "Driver deleted successfully",
  driver_image_not_updated: "Driver image not updated",
  get_driver_successfully: "Get driver data successfully",
  product_added_successfully: "Product added successfully",
  product_get_successfully: "Product get successfully",
  product_data_not_found: "Product data not found",
  product_update_successfully: "Product update successfully",
  product_update_fail: "Product update fail",
  product_delete_successfully: "Product delete successfully",
  product_delete_fail: "Product delete fail",
  task_added_successfully: "Task added successfully",
  task_get_successfully: "Task get successfully",
  task_not_found: "Task not found.",
  task_update_successfully: "Task update successfully.",
  task_completed_successfully: "Task marked as completed successfully.",
  task_canceled_successfully: "Task marked as canceled successfully.",
  task_is_not_scheduled_for_completion_on_this_date:
    "Task is not scheduled for completion on this date.",
  a_task_with_the_same_name_repeat_frequency_and_time_range_already_exists:
    "A task with the same name, repeat frequency, and time range already exists.",
  cart_not_found: "Cart not found",
  cart_updated_successfully: "Cart updated successfully",
  cart_quantity_updated_successfully: "Cart quantity updated successfully",
  cart_deleted_successfully: "Cart deleted successfully",
  product_already_added_into_cart: "OOPS!, Product already added into cart",
  address_added_successfully: "Address added successfully",
  address_not_found: "Address not found",
  address_updated_successfully: "Address updated successfully",
  promo_code_added_successfully: "Promo code added successfully",
  promo_code_get_successfully: "Promo code get data successfully",
  promo_code_updated_successfully: "Promo code update successfully",
  promo_code_deleted_successfully: "Promo code delete successfully",
  promo_code_not_found: "Promo code not found",
  get_user_successfully: "Get user successfully",
  get_dashboard_successfully: "get dashboard data successfully",
  delivery_added_successfully: "Delivery added successfully",
  delivery_get_successfully: "Delivery get successfully",
  delivery_get_by_id_successfully: "Delivery get by id successfully",
  delivery_update_successfully: "Delivery update successfully",
  delivery_delete_successfully: "Delivery delete successfully",
  product_not_found: "Product not found",
  out_of_stock: "Out of stock",
  add_order_successfully: "Add Order Successfully!",
  order_get_successfully: "Order get Successfully!",
  order_not_found: "Order not found!",
  order_approved_successfully: "Order approved successfully!",
  checkout_successfully: "Checkout successfully!",
  payment_get_successfully: "payment get successfully!",
  get_category_by_id_product_get_successfully:
    "Get category by id product get successfully",
  get_category_by_id_product_type_get_successfully:
    "Get category by id product type get successfully",
  period_added_successfully: "Period added successfully",
  get_period_successfully: "Get Periods successfully",
};
